"""Add index to email column in users table

Revision ID: 52e4cd684d76
Revises: 
Create Date: 2024-08-21 09:51:22.539824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e4cd684d76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('cart')
    op.drop_table('products')
    op.drop_table('review')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.create_table('review',
    sa.Column('reviewid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customerid'], ['customers.customerid'], name='review_customerid_fkey'),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], name='review_productid_fkey'),
    sa.PrimaryKeyConstraint('reviewid', name='review_pkey')
    )
    op.create_table('products',
    sa.Column('productid', sa.INTEGER(), server_default=sa.text("nextval('products_productid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('imageurl', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('productid', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cart',
    sa.Column('cartid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customerid'], ['customers.customerid'], name='cart_customerid_fkey'),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], name='cart_productid_fkey'),
    sa.PrimaryKeyConstraint('cartid', name='cart_pkey')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category_id', name='categories_pkey')
    )
    op.create_table('customers',
    sa.Column('customerid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customername', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customerid', name='customers_pkey'),
    sa.UniqueConstraint('email', name='customers_email_key')
    )
    # ### end Alembic commands ###
